#!/usr/bin/env Rscript
suppressPackageStartupMessages({ library(tidyverse) })
args <- commandArgs(trailingOnly = TRUE)
matrix_file <- ifelse(length(args) >= 1, args[1], "results/matrix/pca_matrix_genomes_by_genes.tsv")
metadata_file <- ifelse(length(args) >= 2, args[2], "data/metadata/metadata.tsv")
scores_out <- ifelse(length(args) >= 3, args[3], "results/pca/pca_scores_metadata.tsv")
explained_out <- ifelse(length(args) >= 4, args[4], "results/pca/pca_explained_variance.tsv")
loadings_out <- ifelse(length(args) >= 5, args[5], "results/loadings/pca_loadings.tsv")
dir.create(dirname(scores_out), recursive = TRUE, showWarnings = FALSE)
dir.create(dirname(explained_out), recursive = TRUE, showWarnings = FALSE)
dir.create(dirname(loadings_out), recursive = TRUE, showWarnings = FALSE)
X_df <- read_tsv(matrix_file, show_col_types = FALSE)
metadata <- if (file.exists(metadata_file)) read_tsv(metadata_file, show_col_types = FALSE) else X_df %>% select(genome)
X <- X_df %>% column_to_rownames("genome") %>% as.matrix()
storage.mode(X) <- "numeric"
pca <- prcomp(X, center = TRUE, scale. = FALSE)
explained <- (pca$sdev^2) / sum(pca$sdev^2)
explained_tbl <- tibble(PC = paste0("PC", seq_along(explained)), explained_variance = explained, explained_percent = explained * 100, cumulative_percent = cumsum(explained * 100))
scores <- as.data.frame(pca$x) %>% rownames_to_column("genome") %>% left_join(metadata, by = "genome")
loadings <- as.data.frame(pca$rotation) %>% rownames_to_column("Gene")
write_tsv(scores, scores_out); write_tsv(explained_tbl, explained_out); write_tsv(loadings, loadings_out)
